/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.carlosmonteiro.kafka.avro.autogenerated;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MessageV1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5342589327444723912L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageV1\",\"namespace\":\"com.github.carlosmonteiro.kafka.avro.autogenerated\",\"fields\":[{\"name\":\"experience\",\"type\":[\"int\",\"null\"]},{\"name\":\"age\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageV1> ENCODER =
      new BinaryMessageEncoder<MessageV1>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageV1> DECODER =
      new BinaryMessageDecoder<MessageV1>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MessageV1> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MessageV1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MessageV1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageV1>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MessageV1 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MessageV1 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MessageV1 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MessageV1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Integer experience;
   private int age;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageV1() {}

  /**
   * All-args constructor.
   * @param experience The new value for experience
   * @param age The new value for age
   */
  public MessageV1(java.lang.Integer experience, java.lang.Integer age) {
    this.experience = experience;
    this.age = age;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return experience;
    case 1: return age;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: experience = (java.lang.Integer)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'experience' field.
   * @return The value of the 'experience' field.
   */
  public java.lang.Integer getExperience() {
    return experience;
  }


  /**
   * Sets the value of the 'experience' field.
   * @param value the value to set.
   */
  public void setExperience(java.lang.Integer value) {
    this.experience = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Creates a new MessageV1 RecordBuilder.
   * @return A new MessageV1 RecordBuilder
   */
  public static com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder newBuilder() {
    return new com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder();
  }

  /**
   * Creates a new MessageV1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageV1 RecordBuilder
   */
  public static com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder newBuilder(com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder other) {
    if (other == null) {
      return new com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder();
    } else {
      return new com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder(other);
    }
  }

  /**
   * Creates a new MessageV1 RecordBuilder by copying an existing MessageV1 instance.
   * @param other The existing instance to copy.
   * @return A new MessageV1 RecordBuilder
   */
  public static com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder newBuilder(com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1 other) {
    if (other == null) {
      return new com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder();
    } else {
      return new com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder(other);
    }
  }

  /**
   * RecordBuilder for MessageV1 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageV1>
    implements org.apache.avro.data.RecordBuilder<MessageV1> {

    private java.lang.Integer experience;
    private int age;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.experience)) {
        this.experience = data().deepCopy(fields()[0].schema(), other.experience);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MessageV1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.experience)) {
        this.experience = data().deepCopy(fields()[0].schema(), other.experience);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'experience' field.
      * @return The value.
      */
    public java.lang.Integer getExperience() {
      return experience;
    }


    /**
      * Sets the value of the 'experience' field.
      * @param value The value of 'experience'.
      * @return This builder.
      */
    public com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder setExperience(java.lang.Integer value) {
      validate(fields()[0], value);
      this.experience = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'experience' field has been set.
      * @return True if the 'experience' field has been set, false otherwise.
      */
    public boolean hasExperience() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'experience' field.
      * @return This builder.
      */
    public com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder clearExperience() {
      experience = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder setAge(int value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1.Builder clearAge() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageV1 build() {
      try {
        MessageV1 record = new MessageV1();
        record.experience = fieldSetFlags()[0] ? this.experience : (java.lang.Integer) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageV1>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageV1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageV1>
    READER$ = (org.apache.avro.io.DatumReader<MessageV1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.experience == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.experience);
    }

    out.writeInt(this.age);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 0) {
        in.readNull();
        this.experience = null;
      } else {
        this.experience = in.readInt();
      }

      this.age = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 0) {
            in.readNull();
            this.experience = null;
          } else {
            this.experience = in.readInt();
          }
          break;

        case 1:
          this.age = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










