package com.github.carlosmonteiro.kafka.producer;

import com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1;
import org.apache.kafka.clients.producer.ProducerRecord;

/**
 * @author Carlos Monteiro
 */
public final class ProducerRecordGenerator {

    private static final String MY_KAFKA_TOPIC = "my-kafka-topic";

    private ProducerRecordGenerator() {

    }

    public static ProducerRecord<String, MessageV1> produceMessageV1Record() {
        final var messageV1 = new MessageV1();
        messageV1.setAge(18);
        messageV1.setExperience(100);

        final var producerRecord = new ProducerRecord<>(
                MY_KAFKA_TOPIC,
                "record-key",
                messageV1);

        producerRecord.headers().add("traceId", "12345678".getBytes());
        producerRecord.headers().add("timestamp", String.valueOf(System.currentTimeMillis()).getBytes());

        return producerRecord;
    }
}
