package com.github.carlosmonteiro.kafka.producer;

import com.github.carlosmonteiro.kafka.avro.autogenerated.MessageV1;

import java.util.Scanner;

/**
 * @author Carlos Monteiro
 */
public class Producer {
    public static void main(String[] args) throws InterruptedException {
        final var kafkaMessageProducer = new KafkaMessageProducer<String, MessageV1>();
        final var record = ProducerRecordGenerator.produceMessageV1Record();

        kafkaMessageProducer.send(record);

        Thread.sleep(2000);

        while (true) {
            final var scanner = new Scanner(System.in);
            System.out.print("1 to send another message or 0 to exit: ");
            final var str = scanner.next();

            if ("0".equals(str)) {
                break;
            } else if ("1".equals(str)) {
                kafkaMessageProducer.send(record);
            }
        }
    }
}
